[ci] add action-junit-report to utilize junit xml
The action-junit-report gh action is capable of providing nice test
status output in CI pipelines. Moreover, it can annotate the pull
request contents when a test fails and point to the failing test case
with the error message.

Signed-off-by: Mustafa Kemal Gilor <hello@mkg.dev>

diff --git a/.github/workflows/.ci_meson.yml b/.github/workflows/.ci_meson.yml
--- a/.github/workflows/.ci_meson.yml
+++ b/.github/workflows/.ci_meson.yml
@@ -15,6 +15,9 @@ jobs:
     strategy:
       matrix:
         meson_config: [ 'clang', 'gcc' ]
+    permissions:
+      contents: read
+      checks: write
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -41,6 +44,12 @@ jobs:
         run: meson compile -C tgt
       - name: Run Tests # TODO: Move this to a separate job and add upload build artifacts here 
         run: meson test -C tgt -v
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'tgt/meson-logs/testlog.junit.xml'
+          include_passed: true
       - name: Check format
         run: ninja -C tgt clang-format-check
       - name: Upload Test Log
